### PR TITLE
Make filtering allowed headers case-insensitive

### PR DESCRIPTION
**Pull request by dragarthPl**
## Description

For a reason we can use:
```
AllowedHeadersFilter.WildcardCaseInsensitive.create(strings);
```
I done refactor usage of AllowedHeadersFilter

## Motivation and Context

[#7](https://github.com/Knotx/knotx-commons/issues/7) and [PR-8](https://github.com/Knotx/knotx-commons/pull/8)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style](/CONTRIBUTING.md#coding-conventions) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---
I hereby agree to the terms of the Knot.x Contributor License Agreement.

### CODE REVIEW

**Review by malaskowski — APPROVED** [review]
May I suggest renaming the PR:
> Make filtering allowed headers case-insensitive
?
And please update the changelog with this info (and squash commits as always please).

**Review by malaskowski — COMMENTED** [review]
@dragarth-7 
I'm reviewing https://github.com/Knotx/knotx-commons/pull/8/files and now I wonder if there could be more tests for headers with wildcards here:
https://github.com/Knotx/knotx-commons/blob/master/src/test/java/io/knotx/commons/http/request/AllowedHeadersFilterTest.java#L33
?
E.g. `Host-*` or `Content-*`

**Comment by dragarthPl** [comment]
> May I suggest renaming the PR:
> 
> > Make filtering allowed headers case-insensitive
> > ?
> > And please update the changelog with this info (and squash commits as always please).

Done

> @dragarth-7
> I'm reviewing https://github.com/Knotx/knotx-commons/pull/8/files and now I wonder if there could be more tests for headers with wildcards here:
> https://github.com/Knotx/knotx-commons/blob/master/src/test/java/io/knotx/commons/http/request/AllowedHeadersFilterTest.java#L33
> ?
> E.g. `Host-*` or `Content-*`

I can extend test by more cases. Are you want to discuss about that somewhere ? How will we process it ? By new tickets/topic ?

**Comment by malaskowski** [comment]
Depends what we decide on: https://github.com/Knotx/knotx-fragments/pull/100#issuecomment-585145719

Good start could be creating an issue in the `knotx-commons` to create more unit tests, or you may directly create a PR with more cases (that's also fine). We can discuss there if any more cases should be covered.

**Review by malaskowski — APPROVED** [review]
Thank you @dragarth-7

**Comment by dragarthPl** [comment]
@Skejven You need also merge changes from: https://github.com/Knotx/knotx-commons/pull/14 if you want this changes working.

But i also must remark that in PR-14 from knotx-common we have discussion about that how wildcards/regex mechanizm should work.

See also other related changes that I prepared as PR:
https://github.com/Knotx/knotx-server-http/pull/46
https://github.com/Knotx/knotx-fragments/pull/100
and mentioned above:
https://github.com/Knotx/knotx-commons/pull/14

**Comment by malaskowski** [comment]
Right, thanks my fingers were too quick with merging :)
I will revert and try to re-open this.
I was trusting too much in CI and just discovered this effect: https://github.com/Knotx/knotx-aggregator/issues/25

**Comment by Skejven** [comment]
Right, thanks my fingers were too quick with merging :)
I will revert and try to re-open this.

**Comment by malaskowski** [comment]
@dragarth-7 may I ask you to open a new Pull Request (I can't reopen unfortunately). Sorry for the trouble.

**Pull request merged**
